### ISSUE TITLE
Google Login

### ISSUE THREAD

**Issue by impurefunctions** [officialgdggaborone/ServicesApp#1]
I created the Facebook Login, using Firebase, we can continue by adding the Google login

**Comment by kesegotumisang** [comment]
<img width="1440" alt="Screenshot 2019-03-10 at 04 21 31" src="https://user-images.githubusercontent.com/5565417/54080607-9de91200-42fc-11e9-87c3-ab3683ee0989.png">
Check it out

**Comment by impurefunctions** [comment]
![Screenshot_1552184841](https://user-images.githubusercontent.com/5565417/54080616-cec94700-42fc-11e9-9ecb-d170d13b8cf9.png)
This is the login screen before login

**Comment by impurefunctions** [comment]
![Screenshot_1552191729](https://user-images.githubusercontent.com/5565417/54080626-f91b0480-42fc-11e9-8f62-a91feeee4761.png)
This is after login.. We just have to update the UI with whichever method we used
